version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
 
  node-app:
    build: .
    container_name: node-app
    ports:
      - "3006:3006"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://0.0.0.0:27017/emailwewantya